# 06-02-2026

## Mathematical Operations

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 4, 5, 6])
print("a+b:", a + b)
print("a-b:", a - b)
print("a*b:", a * b)
print("a/b:", a / b)
print("a//b:", a // b)
print("a**b:", a ** b)
print("a%b:", a % b)

a+b: [ 3  5  7  9 11]
a-b: [-1 -1 -1 -1 -1]
a*b: [ 2  6 12 20 30]
a/b: [0.5        0.66666667 0.75       0.8        0.83333333]
a//b: [0 0 0 0 0]
a**b: [    1     8    81  1024 15625]
a%b: [1 2 3 4 5]


In [3]:
arr1 = np.array([3, 4, 2, 6])
arr1+1

array([4, 5, 3, 7])

In [4]:
x = np.array([5, 12, 9, 21])
print(x>10)
print(x>=10)
print(x==10)

[False  True False  True]
[False  True False  True]
[False False False False]


# 11-02-2026

In [3]:
import numpy as np

In [4]:
arr = np.arange(6).reshape(2, 3)

In [5]:
arr.ndim

2

In [6]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr1 = arr.ravel() # ravel returns a flattened array, but it is a view of the original array, so changes to arr1 will affect arr and vice versa

In [8]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr1

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr2 = arr.flatten() # flatten returns a flattened array, but it is a copy of the original array, so changes to arr2 will not affect arr and vice versa

In [11]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
arr2

array([0, 1, 2, 3, 4, 5])

In [13]:
arr[0,1] = 91

In [14]:
arr1

array([ 0, 91,  2,  3,  4,  5])

In [15]:
arr2

array([0, 1, 2, 3, 4, 5])

In [17]:
arr1[0] = 7

In [18]:
arr

array([[ 7, 91,  2],
       [ 3,  4,  5]])

In [19]:
arr2

array([0, 1, 2, 3, 4, 5])

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("hstack:", np.hstack([a, b])) # hstack stacks arrays horizontally (column-wise)
print("vstack:\n", np.vstack([a, b])) # vstack stacks arrays vertically (row-wise)
print("dstack:\n", np.dstack([a, b])) # dstack stacks arrays depth-wise (along the third axis)
print("concatenate axis=0:", np.concatenate([a, b])) # concatenate stacks arrays along the specified axis (default is axis=0)

hstack: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]
dstack:
 [[[1 4]
  [2 5]
  [3 6]]]
concatenate axis=0: [1 2 3 4 5 6]


In [ ]:
A = np.arange(1, 7).reshape(2, 3)
B = np.arange(7, 13).reshape(2, 3)
print("A:\n", A)
print("B:\n", B)
print("hstack 2D:\n", np.hstack([A, B])) # hstack stacks arrays horizontally (column-wise)
print("vstack 2D:\n", np.vstack([A, B])) # vstack stacks arrays vertically (row-wise)
print("dstack 2D:\n", np.dstack([A, B])) # dstack is used to stack arrays along the third axis (depth-wise), so it will create a new dimension and stack A and B along that dimension

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[ 7  8  9]
 [10 11 12]]
hstack 2D:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
vstack 2D:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dstack 2D:
 [[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [ ]:
M = np.arange(8).reshape(2, 4)
print(M)
print(np.split(M, 2, axis=1)) # split splits an array into multiple sub-arrays along the specified axis (default is axis=0), so here we are splitting M into 2 sub-arrays along the columns (axis=1)

[[0 1 2 3]
 [4 5 6 7]]
[array([[0, 1],
       [4, 5]]), array([[2, 3],
       [6, 7]])]


In [37]:
M = np.arange(8).reshape(2, 4)
print(M)
print(np.split(M, 4, axis=1))

[[0 1 2 3]
 [4 5 6 7]]
[array([[0],
       [4]]), array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]])]


In [41]:
M = np.arange(16).reshape(4, 4)
print("M:\n", M)
print("hsplit:\n", np.hsplit(M, 4)) # hsplit splits an array into multiple sub-arrays horizontally (column-wise)
print("vsplit:\n", np.vsplit(M, 4)) # vsplit splits an array into multiple sub-arrays vertically (row-wise)
print("array_split uneven cols (3 Parts):\n", np.array_split(M, 3, axis=1)) # array_split splits an array into multiple sub-arrays along the specified axis (default is axis=0)

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
hsplit:
 [array([[ 0],
       [ 4],
       [ 8],
       [12]]), array([[ 1],
       [ 5],
       [ 9],
       [13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]
vsplit:
 [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
array_split uneven cols (3 Parts):
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2],
       [ 6],
       [10],
       [14]]), array([[ 3],
       [ 7],
       [11],
       [15]])]


In [46]:
x = np.array(["a", "b", "f", "a"])
print("sorted copy:", np.sort(x)) # sort returns a sorted copy of the array, so changes to the sorted array will not affect the original array and vice versa
print("argsort:", np.argsort(x)) # argsort returns the indices that would sort the array, so changes to the sorted array will not affect the original array and vice versa

sorted copy: ['a' 'a' 'b' 'f']
argsort: [0 3 1 2]


# 13-02-2026

In [3]:
y = np.array([5, 0, 7, 0, 9, 0])
print("Where y !=0 -->", np.where(y != 0))
print("Where y ==0 -->", np.where(y == 0))
print("Nonzero -->", np.nonzero(y))

Where y !=0 --> (array([0, 2, 4]),)
Where y ==0 --> (array([1, 3, 5]),)
Nonzero --> (array([0, 2, 4]),)


In [5]:
sorted_arr = np.array([2, 4, 6, 8, 10])
print("Insert positions for [1, 5, 9]:", np.searchsorted(sorted_arr, [1, 5, 9])) # searchsorted returns the indices where the elements should be inserted to maintain order
print("Left vs Right side for equal values:")
dup = np.array([1, 2, 2, 2, 3])
print("Left side for 2:", np.searchsorted(dup, 2, side='left')) # searchsorted with side='left' returns the index of the first occurrence of the value
print("Right side for 2:", np.searchsorted(dup, 2, side='right')) # searchsorted with side='right' returns the index of the last occurrence of the value + 1

Insert positions for [1, 5, 9]: [0 2 4]
Left vs Right side for equal values:
Left side for 2: 1
Right side for 2: 4


In [6]:
sorted_arr = np.array([2, 4, 6, 8, 10])

# Get positions where new values should be inserted
values = [1, 5, 9]
positions = np.searchsorted(sorted_arr, values)

print("Positions:", positions)

# Insert values at the found positions
new_arr = np.insert(sorted_arr, positions, values)
print("New array after insertion:", new_arr)

Positions: [0 2 4]
New array after insertion: [ 1  2  4  5  6  8  9 10]


In [19]:
arr1 = np.array([7, 8, 6, 3, 4, 12])
val = [2, 1, 5, 9]

print("Positions:", np.searchsorted(np.sort(arr1), np.sort(val)))
print("New array after insertion:", np.insert(np.sort(arr1), np.searchsorted(np.sort(arr1), np.sort(val)), np.sort(val)))

Positions: [0 0 2 5]
New array after insertion: [ 1  2  3  4  5  6  7  8  9 12]


In [17]:
arr1 = np.array([7, 8, 6, 3, 4, 12])
val = [2, 1, 5, 9]

arr2 = np.sort(arr1)
print("Sorted array:", arr2)
print("Positions:", np.searchsorted(arr2, np.sort(val)))
print("New array after insertion:", np.insert(arr2, np.searchsorted(arr2, np.sort(val)), np.sort(val)))

Sorted array: [ 3  4  6  7  8 12]
Positions: [0 0 2 5]
New array after insertion: [ 1  2  3  4  5  6  7  8  9 12]
